### ISSUE TITLE
What is our subject

### ISSUE THREAD

**Issue by projectGroup3250Team2** [CS3250Team2/Metro-Info-App#1]

**Comment by Pashweetie** [comment]
Seems like the project we are doing is a mobile app for helping freshmen

**Comment by projectGroup3250Team2** [comment]
Making a web/mobile app for helping freshmen

**Comment by wkramer1** [comment]
Possible resources we can consolidate into our own website:
(Updated 8/29 10:40am)

**Library**: https://library.auraria.edu/
**Auraria Parking**: https://www.ahec.edu/services-departments/parking
**AHEC Finals schedule**: http://dillon.ahec.edu/mastercalendar/MasterCalendar.aspx

**Comment by projectGroup3250Team2** [comment]
Nice
